### PR TITLE
fix build script not working issue.

### LINKED ISSUE #48: /sh_script/build.sh not working.
commit 4480332e9eefdb08e4fecb3dedb899009e5d6345

**current behavior**
/sh_script/build.sh -h start building.
/sh_script/build.sh -r  tests didn't run.

**expected behavior**
/sh_script/build.sh -h dump help message
/sh_script/build.sh -r  start running test.

### PR DESCRIPTION
**Pull request by longlongyang**
fix #48

### CODE REVIEW

File: test/spdm-emu/src/lib.rs [hunk 1]
```diff
@@ -46,5 +46,11 @@ const EMU_FUNCTION_STACK_SIZE: usize = SENDER_BUFFER_SIZE
     + size_of::<SpdmCertChainBuffer>() * SPDM_MAX_SLOT_NUMBER
     + size_of::<usize>() * 256; // for general stack case
 
-pub const EMU_STACK_SIZE: usize =
-    TRANSPORT_STACK_SIZE + DEVICE_IO_STACK_SIZE + SPDM_STACK_SIZE + EMU_FUNCTION_STACK_SIZE;
+#[allow(clippy::identity_op)]
+const ASYNC_RUNTIME_SIZE: usize = 1 * 1024 * 1024; // for executor dispatcher like tokio
```
Comment (jyao1) [inline test/spdm-emu/src/lib.rs:50]: Why this is in emu? not libspdm?

Comment (longlongyang) [reply test/spdm-emu/src/lib.rs:50]: > Why this is in emu? not libspdm?

Because libspdm doesn't involve the async runtime, user may decide to use executor or tokio in emu.
