### PR TITLE
fix mutual authentication failure in requester.

### LINKED ISSUE #63: start session failed when requester do mutual authentication while responder doesn't support.
https://github.com/intel/rust-spdm/blob/fa9e5db37d4a9bb2d38f999d79e5cabae76b3806/spdmlib/src/requester/key_exchange_req.rs#L266

https://github.com/intel/rust-spdm/blob/fa9e5db37d4a9bb2d38f999d79e5cabae76b3806/spdmlib/src/common/session.rs#L316-L322

https://github.com/intel/rust-spdm/blob/fa9e5db37d4a9bb2d38f999d79e5cabae76b3806/spdmlib/src/requester/mutual_authenticate.rs#L21-L30

https://github.com/intel/rust-spdm/blob/fa9e5db37d4a9bb2d38f999d79e5cabae76b3806/spdmlib/src/requester/context.rs#L55-L56

When responder doesn't support mutual authentication, the key_exchange_rsp.mut_auth_req will be 0, resulting in no match with SpdmKeyExchangeMutAuthAttributes and then requester will fail with Err(SPDM_STATUS_INVALID_MSG_FIELD).

### PR DESCRIPTION
**Pull request by longlongyang**
fix #63

### CODE REVIEW

File: spdmlib/src/requester/context.rs [hunk 1]
```diff
@@ -53,9 +53,20 @@ impl RequesterContext {
...
             #[cfg(feature = "mut-auth")]
-            self.session_based_mutual_authenticate(session_id).await?;
-            #[cfg(feature = "mut-auth")]
-            let req_slot_id = Some(self.common.runtime_info.get_local_used_cert_chain_slot_id());
+            let req_slot_id = {
+                if self
+                    .common
+                    .negotiate_info
+                    .rsp_capabilities_sel
+                    .contains(SpdmResponseCapabilityFlags::MUT_AUTH_CAP)
```
Comment (jyao1) [inline spdmlib/src/requester/context.rs:61]: I think we need check both rsp_cap and req_cap.

Comment (longlongyang) [reply spdmlib/src/requester/context.rs:61]: > I think we need check both rsp_cap and req_cap.

Yes, Updated.
