### PR TITLE
fix the Err-variant returned from this function is very large.

### LINKED ISSUE #35: Cargo clippy warning the Err-variant returned from this function is very large
warning: the Err-variant returned from this function is very large
--> spdmlib/src/responder/context.rs:65:10
|
65 | ) -> Result<bool, (usize, [u8; config::DATA_TRANSFER_SIZE])> {
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the Err-variant is at least 4872 bytes
|
= help: try reducing the size of (usize, [u8; _]), for example by boxing large elements or replacing it with Box<(usize, [u8; _])>
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#result_large_err
= note: #[warn(clippy::result_large_err)] on by default

### PR DESCRIPTION
**Pull request by longlongyang**
fix #35

### CODE REVIEW

File: spdmlib/src/responder/context.rs [hunk 1]
```diff
@@ -146,31 +146,25 @@ impl ResponderContext {
         &mut self,
         crypto_request: bool,
         auxiliary_app_data: &[u8],
-    ) -> Result<bool, (usize, [u8; config::RECEIVER_BUFFER_SIZE])> {
-        let mut receive_buffer = [0u8; config::RECEIVER_BUFFER_SIZE];
-        match self
-            .receive_message(&mut receive_buffer[..], crypto_request)
-            .await
-        {
+        raw_packat: &mut [u8],
```
Comment (jyao1) [inline spdmlib/src/responder/context.rs]: 1. raw_packat -> raw_packet.

2. how do you ensure the size of raw_packet is RECEIVER_BUFFER_SIZE?

Comment (longlongyang) [reply spdmlib/src/responder/context.rs]: > 1. raw_packat -> raw_packet.
> 2. how do you ensure the size of raw_packet is RECEIVER_BUFFER_SIZE?

for 2,
spdmlib User -> create device io instance,
spdmlib User -> create raw_packet buffer -> call process massage -> call receive in device io instance,
So basically, It should be the user's responsibility to ensure the size is created and handled properly.
From the view of library, to check the size is optional, I think.

Comment (jyao1) [reply spdmlib/src/responder/context.rs]: What if the input buffer is smaller? Runtime crash?

Comment (longlongyang) [reply spdmlib/src/responder/context.rs]: > What if the input buffer is smaller? Runtime crash?

If the buffer is just smaller a little bit which still can hold the whole payload, then, everything is good. 
And if the buffer is small enough so that it can't cover the whole payload, it may crash in the receive function defined in device io instance (out of range), this is defined by user. If the receive function is handled properly, like return an error status, spdmlib will not crash.

Comment (longlongyang) [reply spdmlib/src/responder/context.rs]: > 1. raw_packat -> raw_packet.
> 2. how do you ensure the size of raw_packet is RECEIVER_BUFFER_SIZE?

For 1, it is updated in latest commit.

Comment (jyao1) [reply spdmlib/src/responder/context.rs]: crash is only the mitigation to avoid exploitation. crash is not allowed by design.
We need check the length to avoid crash.

Comment (longlongyang) [reply spdmlib/src/responder/context.rs]: > crash is only the mitigation to avoid exploitation. crash is not allowed by design. We need check the length to avoid crash.

updated, in latest commit, the length will be checked during build by compiler.
