### PR TITLE
propagate the error back in responder commands.

### LINKED ISSUE #44: need propagate the error back to handle_spdm_xxx function
Currently, in responder code, the write_xxx function doesn't propagate the error back to handle_spdm_xxx function. 
For example:

https://github.com/jyao1/rust-spdm/blob/746d38ea54875121a0ef036fd0c7bb722fc7ee41/spdmlib/src/responder/algorithm_rsp.rs#L13-L18

if some error happens inside `self.write_spdm_algorithm(bytes, &mut writer); ` , line 17 will still be called, a unexpected buffer will be sent to requester, and if the send is good, then handle_spdm_algorithm will return Ok result.

### PR DESCRIPTION
**Pull request by longlongyang**
fix #44

### CODE REVIEW

File: spdmlib/src/responder/capability_rsp.rs [hunk 1]
```diff
@@ -15,17 +18,22 @@ impl ResponderContext {
...
+        bytes: &[u8],
+        writer: &'a mut Writer,
+    ) -> (SpdmResult, Option<&'a [u8]>) {
         if self.common.runtime_info.get_connection_state()
             != SpdmConnectionState::SpdmConnectionAfterVersion
         {
             self.write_spdm_error(SpdmErrorCode::SpdmErrorUnexpectedRequest, 0, writer);
-            return;
+            return (
+                Err(SPDM_STATUS_INVALID_STATE_PEER),
```
Comment (jyao1) [inline spdmlib/src/responder/capability_rsp.rs:35]: This is redundant, because the error status is already included in message.

Suggest to change 1st param to processing state. It should be success, if error response is created.

Please check libspdm.

Comment (longlongyang) [reply spdmlib/src/responder/capability_rsp.rs:35]: > This is redundant, because the error status is already included in message.
> 
> Suggest to change 1st param to processing state. It should be success, if error response is created.
> 
> Please check libspdm.

updated, in latest commit,
the 1st param is removed, kept only the second one,
return None means the message is considered dropped, Some means should send back the response, which includes successful response + error response.

Comment (longlongyang) [reply spdmlib/src/responder/capability_rsp.rs:35]: updated again, with 1st param added back, but return only Ok(()) in the 1st param.
